# ============================================================================
# LLM-Shield Service Account Configuration
# ============================================================================
# IAM service account with least-privilege permissions for Cloud Run.
#
# Apply:
#   gcloud iam service-accounts create llm-shield-sa \
#     --display-name="LLM-Shield Service Account" \
#     --description="Service account for LLM-Shield unified service"
#
#   gcloud projects add-iam-policy-binding ${PROJECT_ID} \
#     --member="serviceAccount:llm-shield-sa@${PROJECT_ID}.iam.gserviceaccount.com" \
#     --role="roles/secretmanager.secretAccessor"
#
#   gcloud projects add-iam-policy-binding ${PROJECT_ID} \
#     --member="serviceAccount:llm-shield-sa@${PROJECT_ID}.iam.gserviceaccount.com" \
#     --role="roles/cloudtrace.agent"
#
#   gcloud projects add-iam-policy-binding ${PROJECT_ID} \
#     --member="serviceAccount:llm-shield-sa@${PROJECT_ID}.iam.gserviceaccount.com" \
#     --role="roles/logging.logWriter"
# ============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-shield-sa
  labels:
    app: llm-shield
    component: service-account
spec:
  displayName: LLM-Shield Service Account
  description: |
    Least-privilege service account for the LLM-Shield unified service.
    This account does NOT have database access - all persistence via ruvector-service.

# Required IAM Roles (Least Privilege)
roles:
  # Access secrets from Secret Manager (RUVECTOR_SERVICE_URL, RUVECTOR_API_KEY, TELEMETRY_ENDPOINT)
  - roles/secretmanager.secretAccessor

  # Write traces to Cloud Trace
  - roles/cloudtrace.agent

  # Write logs to Cloud Logging
  - roles/logging.logWriter

  # Invoke Cloud Run services (for ruvector-service)
  - roles/run.invoker

# Explicitly NOT granted (for security):
notGranted:
  # NO direct database access
  - roles/cloudsql.client
  - roles/cloudsql.editor
  - roles/cloudsql.admin

  # NO storage access (not needed)
  - roles/storage.objectViewer
  - roles/storage.objectAdmin

  # NO Pub/Sub access (not needed)
  - roles/pubsub.publisher
  - roles/pubsub.subscriber

  # NO IAM management
  - roles/iam.serviceAccountUser
  - roles/iam.serviceAccountAdmin
